up:
	docker-compose up
down:
	docker-compose down
up-build:
	docker-compose build && docker-compose up
makemigrations:
	docker-compose run --rm app sh -c "python manage.py makemigrations"
migrate:
	docker-compose run --rm app sh -c "python manage.py migrate"
test:
	docker-compose run --rm app sh -c "python manage.py test"
flake:
	docker-compose run --rm app sh -c "flake8"


